apiVersion: v1
kind: Service
metadata:
  labels:
    name: assadldn-app
  name: assadldn-app-svc
  namespace: assadldn
spec:
  type: LoadBalancer
  selector:
    app: assadldn-app
  ports:
  - name: http
    protocol: TCP
    port: 3000
    #nodePort: 30001
    targetPort: 3000
