apiVersion: v1
kind: Service
metadata:
  labels:
    name: insecure-bank-andres
  name: insecure-bank-andres-svc
  namespace: ag-dev
spec:
  type: NodePort
  ports:
  - name: http
    port: 3000
    nodePort: 30001
    targetPort: 3000
    protocol: TCP
  selector:
    app: insecure-bank-andres
