apiVersion: v1
kind: Service
metadata:
  labels:
    name: allthingsclowd-app
  name: allthingsclowd-app-svc
  namespace: allthingsclowd
spec:
  type: LoadBalancer
  selector:
    app: allthingsclowd-app
  ports:
  - name: http
    protocol: TCP
    port: 3000
    #nodePort: 30001
    targetPort: 3000
