apiVersion: v1
kind: Service
metadata:
  labels:
    name: nodejs-app
  name: nodejs-app-svc
  namespace: ag-dev
spec:
  type: LoadBalancer
  selector:
    app: nodejs-app
  ports:
  - name: http
    protocol: TCP
    port: 3000
    #nodePort: 30001
    targetPort: 3000
    
  
