apiVersion: v1
kind: Service
metadata:
  labels:
    name: insecure-bank-andres
  name: insecure-bank-andres-svc
  namespace: ag-dev
spec:
  type: LoadBalancer
  selector:
    app: insecure-bank-andres
  ports:
  - name: http
    protocol: TCP
    port: 3000
    #nodePort: 30001
    targetPort: 3000
    
  
